// MFCActiveXControl1.idl: ActiveX 컨트롤 프로젝트의 형식 라이브러리 소스입니다.

// 이 파일은 MIDL 컴파일러 도구에 의해 처리되어
// MFCActiveXControl1.ocx에서 리소스가 되는 형식 라이브러리(MFCActiveXControl1.tlb)를
// MFCActiveXControl1.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(d52bb0d7-a328-44c5-bef8-21a244896a2d), version(1.0),
  control ]
library MFCActiveXControl1Lib
{
	importlib(STDOLE_TLB);

	//  CMFCActiveXControl1Ctrl의 기본 디스패치 인터페이스
	[ 
		uuid(9ed9f641-d8fc-4391-8dd3-b0affd1f2ca8)
	]
	dispinterface _DMFCActiveXControl1
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  CMFCActiveXControl1Ctrl의 이벤트 디스패치 인터페이스

	[ 
		uuid(460ce216-5fb3-4533-be80-1cc1dd6a9d1c)
	]
	dispinterface _DMFCActiveXControl1Events
	{
		properties:
			//  이벤트 인터페이스에 속성이 없습니다.

		methods:
	};

	//  CMFCActiveXControl1Ctrl에 대한 클래스 정보
	[
		uuid(9f093275-16a5-4659-9f01-b40f49bcf80a)
	]
	coclass MFCActiveXControl1
	{
		[default] dispinterface _DMFCActiveXControl1;
		[default, source] dispinterface _DMFCActiveXControl1Events;
	};

};
